language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - rvm use 2.1.0
  - gem install bundler
  - bundle install
install:
  - npm install
  - bower install
before_script:
  - grunt sass
  - grunt coffee
  - grunt uglify
script:
  - npm test
  - rake
